In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\PAUL\Desktop\dataset\Position_Salaries_new.csv")

In [3]:
df.head()

,Position,Level,Band,Department,Salary ($),Annual Bonus ($),Bonus %,Total Compensation ($),Years of Experience,Headcount,Remote Eligible,Education Requirement
0,Intern,0,Entry,Operations,25000,1250,0.05,26250.0,0,32,No,High School
1,Business Analyst,1,Entry,Analytics,45000,2250,0.05,47250.0,1,37,No,Bachelor's
2,Junior Consultant,2,Entry,Consulting,50000,4500,0.09,54500.0,4,36,No,Bachelor's
3,Data Analyst,2,Entry,Analytics,52000,4160,0.08,56160.0,3,39,No,Bachelor's
4,HR Coordinator,2,Entry,Human Resources,48000,4320,0.09,52320.0,2,13,No,Bachelor's

In [4]:
df.shape

(100, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Position                100 non-null    object
 1   Level                   100 non-null    int64
 2   Band                    100 non-null    object
 3   Department              100 non-null    object
 4   Salary ($)              100 non-null    int64
 5   Annual Bonus ($)        100 non-null    int64
 6   Bonus %                 100 non-null    float64
 7   Total Compensation ($)  95 non-null     float64
 8   Years of Experience     100 non-null    int64
 9   Headcount               100 non-null    int64
 10  Remote Eligible         100 non-null    object
 11  Education Requirement   100 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 9.5+ KB

In [6]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
## To group into numerical & Categorical   

cat_col = [col for col in df.columns if df[col].dtype == "object"]
num_col = [col for col in df.columns if df[col].dtype != "object"]

print("Categorial Columns", cat_col)
print("Numerical Columns", num_col)

Categorial Columns ['Position', 'Band', 'Department', 'Remote Eligible', 'Education Requirement']
Numerical Columns ['Level', 'Salary ($)', 'Annual Bonus ($)', 'Bonus %', 'Total Compensation ($)', 'Years of Experience', 'Headcount']

In [9]:
### To check for missing values

df.isnull().sum()

Position                  0
Level                     0
Band                      0
Department                0
Salary ($)                0
Annual Bonus ($)          0
Bonus %                   0
Total Compensation ($)    5
Years of Experience       0
Headcount                 0
Remote Eligible           0
Education Requirement     0
dtype: int64

In [12]:
df= df.drop(columns= ["Remote Eligible"])

In [19]:
df.drop(columns= ["Band","Headcount"])

,Position,Level,Department,Salary ($),Annual Bonus ($),Bonus %,Total Compensation ($),Years of Experience,Education Requirement
0,Intern,0,Operations,25000,1250,0.05,26250.0,0,High School
1,Business Analyst,1,Analytics,45000,2250,0.05,47250.0,1,Bachelor's
2,Junior Consultant,2,Consulting,50000,4500,0.09,54500.0,4,Bachelor's
3,Data Analyst,2,Analytics,52000,4160,0.08,56160.0,3,Bachelor's
4,HR Coordinator,2,Human Resources,48000,4320,0.09,52320.0,2,Bachelor's
...,...,...,...,...,...,...,...,...,...
95,Global Account Manager,5,Sales,113000,9040,0.08,122040.0,13,Master's
96,Growth Marketing Manager,5,Marketing,107000,11770,0.11,118770.0,11,Master's
97,Platform Engineer,4,IT,91000,8190,0.09,99190.0,8,Bachelor's/Master's
98,ML Engineer,5,Analytics,122000,7320,0.06,129320.0,13,Master's
99,Business Intelligence Lead,5,Analytics,119000,15470,0.13,134470.0,11,Master's

In [ ]:
###  df['Total'].fillna(df_clean['Embarked'].mode()[0], inplace=True)

In [20]:
df.to_csv("position_salaries_cleaned.csv", index=False)

In [21]:
df.head()

,Position,Level,Band,Department,Salary ($),Annual Bonus ($),Bonus %,Total Compensation ($),Years of Experience,Headcount,Education Requirement
0,Intern,0,Entry,Operations,25000,1250,0.05,26250.0,0,32,High School
1,Business Analyst,1,Entry,Analytics,45000,2250,0.05,47250.0,1,37,Bachelor's
2,Junior Consultant,2,Entry,Consulting,50000,4500,0.09,54500.0,4,36,Bachelor's
3,Data Analyst,2,Entry,Analytics,52000,4160,0.08,56160.0,3,39,Bachelor's
4,HR Coordinator,2,Entry,Human Resources,48000,4320,0.09,52320.0,2,13,Bachelor's

In [22]:
df.describe()

,Level,Salary ($),Annual Bonus ($),Bonus %,Total Compensation ($),Years of Experience,Headcount
count,100.000000,100.000000,100.000000,100.000000,9.500000e+01,100.00000,100.000000
mean,5.460000,196550.000000,28111.100000,0.121400,2.331966e+05,13.15000,8.510000
std,2.371634,197755.811826,34273.584312,0.054957,2.303865e+05,8.91302,8.324838
min,0.000000,25000.000000,1250.000000,0.050000,2.625000e+04,0.00000,1.000000
25%,4.000000,78750.000000,6865.000000,0.080000,8.828000e+04,5.75000,2.000000
50%,5.000000,117500.000000,12980.000000,0.110000,1.345200e+05,11.00000,6.000000
75%,7.000000,218500.000000,31275.000000,0.150000,2.860600e+05,19.00000,12.000000
max,10.000000,1000000.000000,160000.000000,0.270000,1.160000e+06,32.00000,39.000000